### ISSUE TITLE
Dockerfile chn-app outdated -  Url 502 and needed Php 8

### ISSUE THREAD

**Issue by neumanniTech** [jtl-scx/channel#111]
Hello,
if you run docker-compose up you run into the following problems:

1. The url https://dl.bintray.com is not reachable you get a 502 Gateway
2. Some Dependencies in the composer.json needs php >= 8.0.2
`Problem 1
    - symfony/deprecation-contracts is locked to version v3.0.0 and an update of this package was not requested.
    - symfony/deprecation-contracts v3.0.0 requires php >=8.0.2 -> your php version (7.4.26) does not satisfy that requirement.
  Problem 2
    - symfony/filesystem is locked to version v6.0.0 and an update of this package was not requested.
    - symfony/filesystem v6.0.0 requires php >=8.0.2 -> your php version (7.4.26) does not satisfy that requirement.
  Problem 3
    - symfony/string is locked to version v6.0.1 and an update of this package was not requested.
    - symfony/string v6.0.1 requires php >=8.0.2 -> your php version (7.4.26) does not satisfy that requirement.
  Problem 4
    - psr/cache is locked to version 3.0.0 and an update of this package was not requested.
    - psr/cache 3.0.0 requires php >=8.0.0 -> your php version (7.4.26) does not satisfy that requirement.
  Problem 5
    - symfony/event-dispatcher is locked to version v6.0.1 and an update of this package was not requested.
    - symfony/event-dispatcher v6.0.1 requires php >=8.0.2 -> your php version (7.4.26) does not satisfy that requirement.
  Problem 6
    - symfony/event-dispatcher-contracts is locked to version v3.0.0 and an update of this package was not requested.
    - symfony/event-dispatcher-contracts v3.0.0 requires php >=8.0.2 -> your php version (7.4.26) does not satisfy that requirement.
  Problem 7
    - symfony/finder is locked to version v6.0.0 and an update of this package was not requested.
    - symfony/finder v6.0.0 requires php >=8.0.2 -> your php version (7.4.26) does not satisfy that requirement.
  Problem 8
    - symfony/options-resolver is locked to version v6.0.0 and an update of this package was not requested.
    - symfony/options-resolver v6.0.0 requires php >=8.0.2 -> your php version (7.4.26) does not satisfy that requirement.
  Problem 9
    - symfony/process is locked to version v6.0.0 and an update of this package was not requested.
    - symfony/process v6.0.0 requires php >=8.0.2 -> your php version (7.4.26) does not satisfy that requirement.
  Problem 10
    - symfony/stopwatch is locked to version v6.0.0 and an update of this package was not requested.
    - symfony/stopwatch v6.0.0 requires php >=8.0.2 -> your php version (7.4.26) does not satisfy that requirement.
  Problem 11
    - symfony/filesystem v6.0.0 requires php >=8.0.2 -> your php version (7.4.26) does not satisfy that requirement.
    - friendsofphp/php-cs-fixer v3.4.0 requires symfony/filesystem ^4.4.20 || ^5.0 || ^6.0 -> satisfiable by symfony/filesystem[v6.0.0].
    - friendsofphp/php-cs-fixer is locked to version v3.4.0 and an update of this package was not requested.`

Best regards,
Tobi

**Comment by sleipi** [comment]
Thanks for reporting @neumanniTech 

A fix will be released soon.

**Comment by sleipi** [comment]
@neumanniTech please try to re-create the project running

`composer create-project jtl-scx/channel channel 0.18.0`

We are now using another container for running the app.
Furthermore we are now supporting 8.0.* only (in a few weeks also PHP 8.1)

**Comment by neumanniTech** [comment]
Is working now. Thank you.
